[[plugins]]
repo = 'mattn/emmet-vim'
hook_source = '''
	let g:user_emmet_leader_key='<C-y>'
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'
hook_source = '''
    nnoremap <leader>c :call Flake8()
'''
